name: release

on:
  push:
    tags: "v*"

jobs:
  create-issue:
    name: create issue
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: build changelog
        id: build_changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          AUTHOR: ${{ github.actor }}
          TAG: ${{ github.ref_name }}
          CHANGELOG: ${{ steps.build_changelog.outputs.changes }}

      - name: check tests
        uses: https://github.com/danlevik/unit-demo-cra/blob/master/.github/workflows/testing.yml
