name: release

on:
  push:
    tags: "v*"

jobs:
  create-issue:
    name: create issue
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: build changelog
        id: build_changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: create issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          AUTHOR: ${{ github.actor }}
          TAG: ${{ github.ref_name }}
          CHANGELOG: ${{ steps.build_changelog.outputs.changes }}
        with:
          update_existing: true
      - run: "echo Created issue number ${{ steps.create-issue.outputs.number }}"

  check-tests:
    needs: create-issue
    name: check tests
    uses: danlevik/unit-demo-cra/.github/workflows/testing.yml@master

  deploy:
    needs: [check-tests, create-issue]
    name: deploy on gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: deploy
        id: deploy
        run: |
          git remote set-url origin https://git:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          npx gh-pages -d build -u 'github-actions-bot <support+actions@github.com>'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
